<?php
return [
    'BONUS' => 'bonuses',
    'BONUS_META' => 'bonus_meta',
    'BONUS_CATEGORY' => 'bonus_category',
    'BONUS_CATEGORY_RELATIVE' => 'bonus_category_relative',
    'BONUS_CASINO_RELATIVE' => 'bonus_casino_relative',
    'BONUS_AUTHOR_RELATIVE' => 'bonus_author_relative',

    'CASINO' => 'casinos',
    'CASINO_META' => 'casino_meta',
    'CASINO_CATEGORY' => 'casino_category',
    'CASINO_CATEGORY_RELATIVE' => 'casino_category_relative',
    'CASINO_VENDOR_RELATIVE' => 'casino_vendor_relative',
    'CASINO_PAYMENT_RELATIVE' => 'casino_payment_relative',
    'CASINO_DEPOSIT_RELATIVE' => 'casino_deposit_relative',
    'CASINO_CURRENCY_RELATIVE' => 'casino_currency_relative',
    'CASINO_LANGUAGE_RELATIVE' => 'casino_language_relative',
    'CASINO_CASINO_RELATIVE' => 'casino_casino_relative',
    'CASINO_AUTHOR_RELATIVE' => 'casino_author_relative',

    'GAME' => 'games',
    'GAME_META' => 'game_meta',
    'GAME_CATEGORY' => 'game_category',
    'GAME_CATEGORY_RELATIVE' => 'game_category_relative',
    'GAME_VENDOR_RELATIVE' => 'game_vendor_relative',
    'GAME_CASINO_RELATIVE' => 'game_casino_relative',
    'GAME_AUTHOR_RELATIVE' => 'game_author_relative',

    'NEWS' => 'news',
    'NEWS_META' => 'news_meta',
    'NEWS_CATEGORY' => 'news_category',
    'NEWS_CATEGORY_RELATIVE' => 'news_category_relative',
    'NEWS_CASINO_RELATIVE' => 'news_casino_relative',
    'NEWS_AUTHOR_RELATIVE' => 'news_author_relative',

    'VENDOR' => 'vendors',
    'VENDOR_META' => 'vendor_meta',
    'VENDOR_CATEGORY' => 'vendor_category',
    'VENDOR_CATEGORY_RELATIVE' => 'vendor_category_relative',
    'VENDOR_AUTHOR_RELATIVE' => 'vendor_author_relative',

    'PAYMENT' => 'payments',
    'PAYMENT_META' => 'payment_meta',
    'PAYMENT_CATEGORY' => 'payment_category',
    'PAYMENT_CATEGORY_RELATIVE' => 'payment_category_relative',

    'LANGUAGE' => 'languages',
    'LANGUAGE_META' => 'language_meta',
    'LANGUAGE_CATEGORY' => 'language_category',
    'LANGUAGE_CATEGORY_RELATIVE' => 'language_category_relative',

    'CURRENCY' => 'currencies',
    'CURRENCY_META' => 'currency_meta',
    'CURRENCY_CATEGORY' => 'currency_category',
    'CURRENCY_CATEGORY_RELATIVE' => 'currency_category_relative',

    'AUTHOR' => 'authors',
    'AUTHOR_META' => 'author_meta',
    'AUTHOR_CATEGORY' => 'author_category',
    'AUTHOR_CATEGORY_RELATIVE' => 'author_category_relative',

    'ARTICLE' => 'articles',
    'ARTICLE_META' => 'article_meta',
    'ARTICLE_CATEGORY' => 'article_category',
    'ARTICLE_CATEGORY_RELATIVE' => 'article_category_relative',
    'ARTICLE_AUTHOR_RELATIVE' => 'article_author_relative',
    'ARTICLE_CASINO_RELATIVE' => 'article_casino_relative',
    'ARTICLE_GAME_RELATIVE' => 'article_game_relative',
    'ARTICLE_NEWS_RELATIVE' => 'article_news_relative',

    'FUNNEL' => 'funnels',
    'FUNNEL_META' => 'funnel_meta',
    'FUNNEL_CATEGORY' => 'funnel_category',
    'FUNNEL_CATEGORY_RELATIVE' => 'funnel_category_relative',
    'FUNNEL_AUTHOR_RELATIVE' => 'funnel_author_relative',
    'FUNNEL_CASINO_RELATIVE' => 'funnel_casino_relative',
    'FUNNEL_GAME_RELATIVE' => 'funnel_game_relative',
    'FUNNEL_NEWS_RELATIVE' => 'funnel_news_relative',

    'PAGES' => 'pages',
    'PAGE_AUTHOR_RELATIVE' => 'page_author_relative'
];
